### ISSUE TITLE
no runing

### ISSUE THREAD

**Issue by v8st** [ange007/HTMLp#5]
[DCC Fatal Error] HTMLp.DOMCore.pas(6): F1026 File not found: 'RegularExpressions.dcu'

**Comment by dimmaq** [comment]
Delphi version?
Regular expression come to delphi since XE (2011)

**Comment by ange007** [comment]
@v8st, for old Delphi version you can use old _(original)_ version: https://github.com/ange007/HTMLp/tree/master
